ansible_connection: ansible.netcommon.network_cli
ansible_network_os: cisco.ios.ios
ansible_user: "{{ lookup('env', 'ANSIBLE_NET_USERNAME') }}"
ansible_password: "{{ lookup('env', 'ANSIBLE_NET_PASSWORD') }}"
ansible_become: yes
ansible_become_method: enable
ansible_become_password: "{{ lookup('env', 'ANSIBLE_NET_ENABLE_PASSWORD') }}"

